### ISSUE TITLE
Applying Sharp placeholder

### ISSUE THREAD

**Issue by kylesloper** [saneef/eleventy-plugin-img2picture#11]
Hello, I want to apply a sharp placeholder to the images generated by this plugin.

See this issue for the specific placeholder manipulation that we are after.
https://github.com/lovell/sharp/issues/1532

Is it possible to apply existing sharp placeholder options to this plugin or will an external library be required?

Thanks,

**Comment by saneef** [comment]
In the [`options`](https://github.com/saneef/eleventy-plugin-img2picture#options), you can use `sharpOptions` to pass on options to Sharp. 

Does that work for your use case?
