### ISSUE TITLE
Plugin messes with markup when `<body>` attribute names have special characters

### ISSUE THREAD

**Issue by nford** [saneef/eleventy-plugin-img2picture#16]
I've attached a zip archive of a test project to demonstrate this issue. If you comment-out the plugin in .eleventy.js and run `yarn start`, the html is generated fully but no images generated (obviously). If you enable the img2picture config again in .eleventy.js  the plugin does its thing, generates images, but the only thing in the html file is the picture - layouts/base.njk is not included in the resulting index.html file.  As far as I can tell I have configured the plugin correctly. What is it that it does not like about my sample config? 

    const img2picture = require("eleventy-plugin-img2picture");
    
    module.exports = config => {
        config.addPlugin(img2picture, {
            eleventyInputDir: "./src",
            imagesOutputDir: "./dist/images/processed",
            urlPath: "/images/processed",
            filenameFormat: function (id, src, width, format, options) {
                return `${id}-${width}.${format}`;
            }
        });

        return {
            templateFormats: ["md", "njk", "html"],
            markdownTemplateEngine: 'njk',
            dataTemplateEngine: 'njk',
            htmlTemplateEngine: 'njk',
            dir: {
                input: './src',
                output: './dist',
                includes: "_includes"
            }
        };
    };

[img2picture-test.zip](https://github.com/saneef/eleventy-plugin-img2picture/files/8829016/img2picture-test.zip)

**Comment by nford** [comment]
This bug seems to go back at least to 0.2.0 based on my testing.

**Comment by saneef** [comment]
Looks to me, in `src/_includes/layouts/base.njk` the starting `<body>` tag is not having its closing bracket (`>` is missing). Adding that bracket seems to resolve the issue for me.

```diff
--- a/src/_includes/layouts/base.njk
+++ b/src/_includes/layouts/base.njk
@@ -6,7 +6,7 @@ type: page
    <head>
      <title>{{ title }}</title>
    </head>
    [-<body-]{+<body>+}
      <main>
          {{ content | safe }}
      </main>
```

This plugin parse the HTML files generated by Eleventy to convert `<img>` tags to `<picture>` tags. I suspect when it doesn't find a valid `<body>` block, it ignores `<head>` and other tags.

In another note, in `home.njk` you are using `<img class="" src={{ image }}/>`. I would recommend using quote on all attributes in the Nunjucks. E.g.: `<img class="" src="{{ image }}" />`. In case, the `image` path have space in the file name, the generated HTML tag becomes invalid.

**Comment by nford** [comment]
Thanks for your reply Saneef and for pointing out that error, it led me to find the actual cause of the issue in my real project. Replace the body tag with this:

    <body x-on:keydown.escape="isModalOpen=false">

That's alpine.js which worked without issue until I added your plugin.

**Comment by saneef** [comment]
I'll check whether the plugin messes with Alpine.js tags.

**Comment by saneef** [comment]
I published another version [`v2.0.3`](https://www.npmjs.com/package/eleventy-plugin-img2picture/v/2.0.3). This should fix the problem.

**Comment by nford** [comment]
That did it! Thank you, Saneef

**Comment by saneef** [comment]
Glad it did the trick. Thanks for taking time to test the releases!
