### ISSUE TITLE
Make moving classes to picture tag optional

### ISSUE THREAD

**Issue by nford** [saneef/eleventy-plugin-img2picture#18]
According to MDN (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture)

    The <img> element serves two purposes:

    It describes the size and other attributes of the image and its presentation.
    It provides a fallback in case none of the offered <source> elements are able to provide a usable image.

the `<img>` tag within a `<picture> `tag is still used to display whichever source is selected by the browser. Because of this the classes should still be on the `<img>` tag for full "styleability" or there should be a flag enabling the user to keep classes on the `<img>` tag.

In my case I am unable to achieve the same styling effect using Tailwind classes on an image using img2picture that I previously could but when I manually move the classes to the `<img>` tag with developer tools it works.

Another reason to do this is that in the case of a browser compatibility issue with `<picture>`, the `<img>` will still have styling.

**Comment by saneef** [comment]
I write styles like `img, picture > img { ... }`, and it works for `img` elements that are standalone and wrapped with `<picture>`. I understand that it won't be possible with Tailwind and other utility class-based styling methods.

I'm thinking a loud here. Please share your inputs.

The approach I have in mind is: 
1. Add a boolean option `hoistClass` (I'll talk about the default value in a bit). When `true`, the classes are moved from `<img>` to `<picture>`, the way it is right now. When it is `false`, retain the `class` on `<img>`. 
2. The `<picture>` element has `display: inline` by default. Usually, you might want to apply `display: block` or similar styles. Here I'm thinking two ways to add classes to `<picture>`: 
	1. A global way: add an option `pictureClass`, a string. This will be added as `class` attribute in the `<picture>`. _This only works when `hoistClass` is `false`._ 
	2. Additionally, a case-by-case way: provide `data-img2picture-picture-class` attribute on `<img>`. This again is string like `pictureClass`. This again will be applied to parent `<picture>` _when `hoistClass` is `false`._ 

Should the `hoistClass` be on or off by default? 

Keeping it off won't be a breaking change. People who are updating from previous version can use without any changes in the configuration. Switching it on by default will be a breaking change.

The feature of `hoistClass`, moving class names from `<img>` to its parent `<picture>` should be an explicit choice by the user. Currently, it is hoisted by the plugin, and it may break CSS styling like you faced. When I created, I hadn't put enough thinking and copied the way it is done in [eleventy-plugin-local-respimg](https://github.com/chromeos/static-site-scaffold-modules/tree/main/modules/eleventy-plugin-local-respimg).

I feel `hostClass` should be `false` by default.

**Comment by nford** [comment]
That all looks good to me. If having hoistClass false by default isn't a breaking change it will definitely be a more seamless experience for the user going forward so they don't have to customize any CSS for the plugin. I think it's best for the plugin to do nothing with styles by default. This is good.

**Comment by saneef** [comment]
Hey, I have published a new version with above features [`v3.0.0`](https://github.com/saneef/eleventy-plugin-img2picture/releases/tag/v3.0.0).

A couple of minor changes form the above write up:
1. Renamed option `hoistClass` to `hoistImgClass`.
1. The class names provided for `<picture>` element either through `pictureClass` option or `data-img2picture-picture-class` attribute on `<img>` will be retained irrespective of the values provided in `hoistImgClass`. I don't want to create a confusion.

See if this new release works for you.

**Comment by nford** [comment]
This works great! Thanks Saneef - this has also made my build times much faster

**Comment by nford** [comment]
This works great! Thanks Saneef - this has also made my build times much faster

**Comment by nford** [comment]
This works great! Thanks Saneef - this has also made my build times much faster
