### ISSUE TITLE
caching generated images

### ISSUE THREAD

**Issue by michael-voit** [saneef/eleventy-plugin-img2picture#20]
Hey Saneef,

hope addressing and discussing that here on GitHub is the right place.

If I do understand that right - from the README.md and from playing around with the options, the option "cacheOptions" is for specifying settings for the cache related to the fetch option - so to cache fetched remote images.

It is NOT - please correct me if I am wrong and tell me, what I have not seen or understood - to cache the images generated via the plugin.

Is a functionality like that planned or on the roadmap?

Because I think it would be a very good thing regarding to energy usage (climate), build minute budgets (small organizations) and so on.

Happy to read your thoughts about that. :)

**Comment by michael-voit** [comment]
Hey Saneef,

I have a good solution now. I think the main topic at my side was, that I deleted the whole output folder at the beginning of a new build. I do that with rimraf and deleted everything. Now I use `rimraf _site/!(assets) _site/assets/!(images)` and so the images are staying there if I do not delete them by hand - and then they are not created anew. :) At the build pipeline in the cloud I set this folder to be cached.

I close the issue here and hope, that at least one person will find help through it. For me it was a public place to think loud.

**Comment by saneef** [comment]
Sorry @michael-voit, I missed replying to your issue. 

Glad that you already figured out.

It's feature in [Eleventy Image,](https://www.11ty.dev/docs/plugins/image/#disk-cache) which this plugin is using internally. As long as you are not deleting the generated image files between builds, the plugin will skip unchanged files.
