### ISSUE TITLE
Can't not have an alt text

### ISSUE THREAD

**Issue by ItsEthanH** [saneef/eleventy-plugin-img2picture#21]
Hello!

First off - amazing plugin. No other gives such fine-grained control over the image output while also being so easy to use.

However, the only thing I haven't been able to do is to pass a value on the img tag to get an alt="" to render.

There are some valid reasons for this - decorative or background images don't need alt text. I've tried passing alt="", alt=" " and looked through the docs for a data- attribute, but all methods still give me validation errors.

Ideally, I'd be able to use a data- attribute or pass alt="" and have alt="" returned (the latter returns alt on it's own, which Google doesn't like).

Let me know if I can provide more info :)

**Comment by saneef** [comment]
Look like a bug.

Thanks for reporting. 

Will work on it soon.

**Comment by saneef** [comment]
This is fixed in [v4.1.1](https://github.com/saneef/eleventy-plugin-img2picture/releases/tag/v4.1.1).
