### ISSUE TITLE
Error building

### ISSUE THREAD

**Issue by Amplificator** [saneef/eleventy-plugin-img2picture#6]
I have added this plugin to my project but I get an error when building it.

I've set it up according to the instructions and added it using:
```
eleventyConfig.addPlugin(img2picture, {
    eleventyInputDir: "", // Eleventy input folder.
    imagesOutputDir: "_site/assets/images/", // Output folder for optimized images.
    // URL prefix for images src URLS.
    // It should match with path suffix in `imagesOutputDir`.
    // Eg: imagesOutputDir with `_site/images` likely need urlPath as `/images/`
    urlPath: "/assets/images/",
    extensions: ["jpg", "png", "jpeg"],
    formats: ["avif", "webp", "jpeg"],
    sizes: "100vw",
    minWidth: 150,
    maxWidth: 1440,
    widthStep: 150,
    fetchRemote: false,
    dryRun: false,

    filenameFormat: function (id, src, width, format) {
      const extension = path.extname(src);
      const name = path.basename(src, extension);

      return `${name}-${id}-${width}w.${format}`;
    }
  });
```
The error I get is as follows:
https://pastebin.mozilla.org/WjARFvy6

All my images are placed in two places, just for testing. So they are in
`assets/images/`
and the output folder
`_site/assets/images`

I have tried setting the input and output directories to all kinds of values but I get the same error all the time.

What am I doing wrong?

**Comment by Amplificator** [comment]
According to the error it looks for an image /assets/images/duelhost.png
Shouldn't it be assets/images/duelhost.png without the first slash?

**Comment by saneef** [comment]
The `eleventyInputDir` should be same as [`dir.input`](https://www.11ty.dev/docs/config/#input-directory) returned in the Eleventy configuration. In case you are not setting any value for `dir.input`, the default value is `"."`. 

`""` is not a valid path. So, can you try with setting the `eleventyInputDir` same value as `dir.input`?

**Comment by Amplificator** [comment]
I don't define dir.input in my config.

I've just added `"."` as eleventyInputDir and now I get this: https://pastebin.mozilla.org/hmbEwC2W

**Comment by saneef** [comment]
@Amplificator Can you share you `.eleventy.js`, or is the project publicly accessible?

**Comment by Amplificator** [comment]
Let's start with the config file: https://pastebin.mozilla.org/SdhxRSDj

If you need the project I upload that later.

**Comment by saneef** [comment]
You don't need to provide `filenameFormat` and other optional parameters. Only `eleventyInputDir`, `imagesOutputDir `, and `urlPath` are the required options.

If you want to use the example `filenameFormat` function, you need to include these lines on top of the `.eleventy.js` to work:

```js
const path = require("path");
```

**Comment by Amplificator** [comment]
It works by adding that const, thanks :)

I know that most of these options are optional, but I like having all useful options added, despite them being optional and even fi they are the default values. Because then I know that can be changed, should I need to :)
